sudo: required

language: java

services:
  - docker

before_install:

install:
  - docker build -t james/project dockerfiles/compilation/java-8
  - docker run --env DOCKER_HOST=unix:///var/run/docker.sock -v /var/run/docker.sock:/var/run/docker.sock -v $PWD:/origin -t james/project -s
